config/routes.rb
Rails.application.routes.draw do
  resources :b2s
  resources :posts do
    member do
      post :like_or_unlike_post
    end
  end
  resources :settings
  devise_for :users
  root 'instagram#home_page'
  get 'instagram/landing_page'
  
  
  get 'users/profile' , as: :user_profile
  post 'users/update_profile' , as: :update_user_profile
  
  # post 'friends/friend_request' , as: :friend_request
  
  resources :friends do
    member do
      post :friend_request
      post :approve_request
      post :reject_request
      post :block_or_unfriend
      post :unblock_user
    end
    
    collection do
      get :pending_requests
      get :user_friends
      get :blocked_users
    end
  end
  
  
  post 'suggestion/create_suggestion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/action.rb
class Action < ApplicationRecord
 
    self.table_name = "active_storage_variant_records"

end

app/models/b1.rb
class B1 < ApplicationRecord
end

app/models/b2.rb
class B2 < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
    APPROVE, REJECT, FRIEND, UNFRIEND, PENDING, BLOCK = 'approve', 'reject', 'friend', 'unfriend', 'pending', 'block'
    

    class << self 
      def get_all_pending_requests(current_user)
        User.joins(:friends)
        .where(friends: {friend_id: current_user.id, request_status: 'pending'})
        .pluck('friends.id','users.id','users.email')
      end

      def get_all_user_friends(current_user)
        User.joins(:friends)
        .where('friends.user_id = ? OR friends.friend_id = ?', current_user.id, current_user.id)
        .where(friends: {request_status: Friend::APPROVE})
        .where.not(friends: {friendship_status: Friend::BLOCK})     
        .pluck('friends.id', 'friends.friend_id', 'users.email')
        .map {|friend_tbl_id, friend_id, email| {friend_tbl_id: friend_tbl_id, friend_id: friend_id, email: email}}
      end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_rich_text :content
    has_many_attached :post_images, dependent: :destroy


    has_many :user_like_posts , dependent: :destroy
    has_many :users , through: :user_like_posts

    has_many :suggestions , as: :suggestionable
end

app/models/setting.rb
class Setting < ApplicationRecord
    belongs_to :user
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :user
  belongs_to :suggestionable, polymorphic: true
end

app/models/third_party_api.rb
class ThirdPartyApi < ApplicationRecord
    class << self
        def rest_countries_api
            'https://restcountries.com/v3.1/all'
        end

        def city_api_by_country_name(country_code)
            "http://api.geonames.org/searchJSON?country=#{country_code}&maxRows=1000&username=haris"
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :setting , dependent: :destroy
  has_one_attached :profile_photo, dependent: :destroy
  has_many :friends , dependent: :destroy
  has_many :posts , dependent: :destroy
  has_many :suggestions , dependent: :destroy

# many to many for post likes
  has_many :user_like_posts , dependent: :destroy
  has_many :post , through: :user_like_posts

  after_create do
     Setting.create(user_id: self.id) if self.id.present?
  end      

  def full_name
    first_name.present? || last_name.present? ? "#{first_name} #{last_name}" : email
  end
  
end

app/models/user_like_post.rb
class UserLikePost < ApplicationRecord
    belongs_to :user 
    belongs_to :post
end

app/controllers/a_controller.rb
class AController < ApplicationController




   
    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def friend_request
    return false unless params[:id].present?
    user_request = User.find(params[:id])
    return false if already_sent_request(user_request)
    request = current_user.friends.build(friend_id: user_request.id) if user_request
    if request.save!
       respond_to do |format|
          # format.turbo_stream do
          #  render turbo_stream: [turbo_stream.update("flash" , "Request sent successfully"),
          #                        turbo_stream.update("updated_card", partial: "instagram/slider", locals: {suggestion_user: suggestion_users})]
          # end
          format.html { redirect_to instagram_landing_page_path, notice: "Request sent successfully!" }
       end
    else

    end
  end

  def pending_requests
    @requests = Friend.get_all_pending_requests(current_user)
  end

  def approve_request
     return false unless params[:id]
     record = Friend.find(params[:id])
     record.update(request_status: Friend::APPROVE, friendship_status: Friend::FRIEND) if record.present?
     format.html { redirect_to instagram_landing_page_path, notice: "Request approved successfully!" }
  end

  def reject_request
     return false unless params[:id]
     record = Friend.find(params[:id])
     record.update(request_status: Friend::REJECT, friendship_status: Friend::UNFRIEND) if record.present?
     format.html { redirect_to instagram_landing_page_path, notice: "Request rejected successfully!" }
  end

  def user_friends
    @user_friends = Friend.get_all_user_friends(current_user)
  end

  def block_or_unfriend
    Friend.find(params[:id]).update(request_status: set_request_status, friendship_status: params[:action_performable], blocked_by: blocked_by_user)
  end

  def blocked_users
    @blocked_users = User.joins(:friends)
                         .where(friends: {friendship_status: "block", blocked_by: current_user.id})
                         .pluck("friends.id", "friends.friend_id", "friends.user_id")
                         .map{|friends_tbl_id, friend_id, user_id| {tbl_id: friends_tbl_id, email: user_id == current_user.id ? User.find(friend_id).email : current_user.email } }
  end


  def unblock_user
    Friend.find(params[:id]).update(blocked_by: nil, friendship_status: Friend::FRIEND)
  end
  private
  
  def already_sent_request(user)
    Friend.find_by(user_id: [current_user.id, user.id], friend_id: [user.id, current_user.id], request_status: Friend::PENDING) ? true : false
  end

  def set_request_status
    params[:action_performable] == Friend::UNFRIEND ? nil : Friend::APPROVE
  end

  def blocked_by_user
    params[:action_performable] == Friend::BLOCK ? current_user.id : nil
  end
end

app/helpers/a_helper.rb
module AHelper
end

app/helpers/b1s_helper.rb
module B1sHelper
end

app/helpers/b2s_helper.rb
module B2sHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
    def request_status(u)
      Friend.find_by(user_id: [current_user.id, u.id], friend_id: [u.id, current_user.id], request_status: 'pending').present? ? true : false
    end

    def friend_email(id)
      User.find(id).email
    end
end

app/helpers/instagram_helper.rb
module InstagramHelper
    def page_number(sum)
        sum = sum + 1
    end

    def user_photo(u)
    return "no_photo.webp" unless u.profile_photo
    u.profile_photo if u.profile_photo.present?
    end

    def user_like_this_post(post)
        current_user.user_like_posts.where(post_id: post.id).present?
    end

    def total_likes(post)
      post.user_like_posts.count
    end

    def total_suggestion(post)
        post.suggestions.count
    end
end

app/helpers/posts_helper.rb
module PostsHelper

    def post_user(post)
        post.user == current_user ? 'You' : post.user.email
    end

    def users_post(post)
       post.user == current_user
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/suggestion_helper.rb
module SuggestionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/blocked_users.html.erb
<%= turbo_frame_tag :modal do %>
    <div style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: #fff; border: 1px solid #000; padding: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); z-index: 999;">
    <%= link_to 'Back' , :back %>
    <h1>Blocked Users</h1>
    <% @blocked_users.each do |user| %>
        <span style="display: inline-block;">
         <%= user[:email] %>
         </span>
         <span style="display: inline-block;">
           <%= button_to 'Unblock' , unblock_user_friend_path(user[:tbl_id])  %>
         </span>
         <br>
       <% end %> 
    </div>
  
  <% end %>
  
  

app/views/friends/pending_requests.html.erb
<%= turbo_frame_tag :modal do %>
    <div style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: #fff; border: 1px solid #000; padding: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); z-index: 999;">
    <%= link_to 'Back' , :back %>
    <h1>New Friend Requests</h1>
    <% @requests.each do |req| %>
      <span style="display: inline-block;">
         <%= req[2] %>
       </span>
       <span style="display: inline-block;">
         <%= button_to 'Approve' , approve_request_friend_path(req[0]), method: :post %>
       </span>
       <span style="display: inline-block;">
         or
       </span>
       <span style="display: inline-block;">
         <%= button_to 'Reject' , reject_request_friend_path(req[0]), method: :post %>
       </span>
       <br>
     <% end %> 
    </div>
  
  <% end %>
  
  

app/views/friends/user_friends.html.erb
<%= turbo_frame_tag :modal do %>

    <div style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: #fff; border: 1px solid #000; padding: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); z-index: 999;">
    <%= link_to 'Back' , :back %>
    <h1>Friends Management</h1>
    <% @user_friends.each do |usr| %>
      <span style="display: inline-block;">
       </span>
      <span style="display: inline-block;">

         <% if usr[:email] == current_user.email %>
            <%= friend_email(usr[:friend_id]) %>
          <% else %>
         <%= usr[:email] %>
          <% end %>
       </span>
       <span style="display: inline-block;">
         <%= button_to 'Unfriend' , block_or_unfriend_friend_path(id: usr[:friend_tbl_id], action_performable: Friend::UNFRIEND)  %>
       </span>
       <span style="display: inline-block;">
         or
       </span>
       <span style="display: inline-block;">
         <%= button_to 'Block' ,  block_or_unfriend_friend_path(id: usr[:friend_tbl_id], action_performable: Friend::BLOCK) %>
       </span>
       <br>
     <% end %> 
    </div>
<% end %>