config/routes.rb
Rails.application.routes.draw do
  resources :b2s
  resources :posts do
    member do
      post :like_or_unlike_post
    end
  end
  resources :settings
  devise_for :users
  root 'instagram#home_page'
  get 'instagram/landing_page'
  
  
  get 'users/profile' , as: :user_profile
  post 'users/update_profile' , as: :update_user_profile
  
  # post 'friends/friend_request' , as: :friend_request
  
  resources :friends do
    member do
      post :friend_request
      post :approve_request
      post :reject_request
      post :block_or_unfriend
      post :unblock_user
    end
    
    collection do
      get :pending_requests
      get :user_friends
      get :blocked_users
    end
  end
  
  
  post 'suggestion/create_suggestion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/action.rb
class Action < ApplicationRecord
 
    self.table_name = "active_storage_variant_records"

end

app/models/b1.rb
class B1 < ApplicationRecord
end

app/models/b2.rb
class B2 < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
    APPROVE, REJECT, FRIEND, UNFRIEND, PENDING, BLOCK = 'approve', 'reject', 'friend', 'unfriend', 'pending', 'block'
    

    class << self 
      def get_all_pending_requests(current_user)
        User.joins(:friends)
        .where(friends: {friend_id: current_user.id, request_status: 'pending'})
        .pluck('friends.id','users.id','users.email')
      end

      def get_all_user_friends(current_user)
        User.joins(:friends)
        .where('friends.user_id = ? OR friends.friend_id = ?', current_user.id, current_user.id)
        .where(friends: {request_status: Friend::APPROVE})
        .where.not(friends: {friendship_status: Friend::BLOCK})     
        .pluck('friends.id', 'friends.friend_id', 'users.email')
        .map {|friend_tbl_id, friend_id, email| {friend_tbl_id: friend_tbl_id, friend_id: friend_id, email: email}}
      end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_rich_text :content
    has_many_attached :post_images, dependent: :destroy


    has_many :user_like_posts , dependent: :destroy
    has_many :users , through: :user_like_posts

    has_many :suggestions , as: :suggestionable
end

app/models/setting.rb
class Setting < ApplicationRecord
    belongs_to :user
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :user
  belongs_to :suggestionable, polymorphic: true
end

app/models/third_party_api.rb
class ThirdPartyApi < ApplicationRecord
    class << self
        def rest_countries_api
            'https://restcountries.com/v3.1/all'
        end

        def city_api_by_country_name(country_code)
            "http://api.geonames.org/searchJSON?country=#{country_code}&maxRows=1000&username=haris"
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :setting , dependent: :destroy
  has_one_attached :profile_photo, dependent: :destroy
  has_many :friends , dependent: :destroy
  has_many :posts , dependent: :destroy
  has_many :suggestions , dependent: :destroy

# many to many for post likes
  has_many :user_like_posts , dependent: :destroy
  has_many :post , through: :user_like_posts

  after_create do
     Setting.create(user_id: self.id) if self.id.present?
  end      

  def full_name
    first_name.present? || last_name.present? ? "#{first_name} #{last_name}" : email
  end
  
end

app/models/user_like_post.rb
class UserLikePost < ApplicationRecord
    belongs_to :user 
    belongs_to :post
end

app/controllers/a_controller.rb
class AController < ApplicationController




   
    
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: %i[ show edit update destroy ]

  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings or /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully created." }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1 or /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to setting_url(@setting), notice: "Setting was successfully updated." }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1 or /settings/1.json
  def destroy
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url, notice: "Setting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setting_params
      params.require(:setting).permit(:public, :someone_can_comment_on_post, :someone_can_search_me, :someone_can_mention_me, :account_status, :show_me_in_suggestions)
    end
end

app/helpers/a_helper.rb
module AHelper
end

app/helpers/b1s_helper.rb
module B1sHelper
end

app/helpers/b2s_helper.rb
module B2sHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
    def request_status(u)
      Friend.find_by(user_id: [current_user.id, u.id], friend_id: [u.id, current_user.id], request_status: 'pending').present? ? true : false
    end

    def friend_email(id)
      User.find(id).email
    end
end

app/helpers/instagram_helper.rb
module InstagramHelper
    def page_number(sum)
        sum = sum + 1
    end

    def user_photo(u)
    return "no_photo.webp" unless u.profile_photo
    u.profile_photo if u.profile_photo.present?
    end

    def user_like_this_post(post)
        current_user.user_like_posts.where(post_id: post.id).present?
    end

    def total_likes(post)
      post.user_like_posts.count
    end

    def total_suggestion(post)
        post.suggestions.count
    end
end

app/helpers/posts_helper.rb
module PostsHelper

    def post_user(post)
        post.user == current_user ? 'You' : post.user.email
    end

    def users_post(post)
       post.user == current_user
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/suggestion_helper.rb
module SuggestionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.label :someone_can_comment_on_my_post, style: "display: block" %>
    <%= form.check_box :someone_can_comment_on_post %>
  </div>

  <div>
    <%= form.label :someone_can_search_me, style: "display: block" %>
    <%= form.check_box :someone_can_search_me %>
  </div>

  <div>
    <%= form.label :someone_can_mention_me, style: "display: block" %>
    <%= form.check_box :someone_can_mention_me %>
  </div>

  <div>
    <%= form.label :account_status, style: "display: block" %>
    <%= form.check_box :account_status %>
  </div>

  <div>
    <%= form.label :show_me_in_suggestions, style: "display: block" %>
    <%= form.check_box :show_me_in_suggestions %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/_setting.html.erb
<div id="<%= dom_id setting %>">
  <p>
    <strong>Public:</strong>
    <%= setting.public %>
  </p>

  <p>
    <strong>Someone can comment on post:</strong>
    <%= setting.someone_can_comment_on_post %>
  </p>

  <p>
    <strong>Someone can search me:</strong>
    <%= setting.someone_can_search_me %>
  </p>

  <p>
    <strong>Someone can mention me:</strong>
    <%= setting.someone_can_mention_me %>
  </p>

  <p>
    <strong>Account status:</strong>
    <%= setting.account_status %>
  </p>

  <p>
    <strong>Show me in suggestions:</strong>
    <%= setting.show_me_in_suggestions %>
  </p>

</div>

app/views/settings/edit.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="modal" data-action="turbo:submit-end->modal#closeModal" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: #fff; border: 1px solid #000; padding: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); z-index: 999;">
  <h1>Setting</h1>

<%= render "form", setting: @setting %>
<%= link_to 'Close' , :back %>
<br>

</div>

<% end %>

app/views/settings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Settings</h1>

<div id="settings">
  <% @settings.each do |setting| %>
    <%= render setting %>
    <p>
      <%= link_to "Show this setting", setting %>
    </p>
  <% end %>
</div>

<%= link_to "New setting", new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render "form", setting: @setting %>

<br>

<div>
  <%= link_to "Back to settings", settings_path %>
</div>

app/views/settings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @setting %>

<div>
  <%= link_to "Edit this setting", edit_setting_path(@setting) %> |
  <%= link_to "Back to settings", settings_path %>

  <%= button_to "Destroy this setting", @setting, method: :delete %>
</div>