config/routes.rb
Rails.application.routes.draw do
  resources :b2s
  resources :posts do
    member do
      post :like_or_unlike_post
    end
  end
  resources :settings
  devise_for :users
  root 'instagram#home_page'
  get 'instagram/landing_page'
  
  
  get 'users/profile' , as: :user_profile
  post 'users/update_profile' , as: :update_user_profile
  
  # post 'friends/friend_request' , as: :friend_request
  
  resources :friends do
    member do
      post :friend_request
      post :approve_request
      post :reject_request
      post :block_or_unfriend
      post :unblock_user
    end
    
    collection do
      get :pending_requests
      get :user_friends
      get :blocked_users
    end
  end
  
  
  post 'suggestion/create_suggestion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/action.rb
class Action < ApplicationRecord
 
    self.table_name = "active_storage_variant_records"

end

app/models/b1.rb
class B1 < ApplicationRecord
end

app/models/b2.rb
class B2 < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
    APPROVE, REJECT, FRIEND, UNFRIEND, PENDING, BLOCK = 'approve', 'reject', 'friend', 'unfriend', 'pending', 'block'
    

    class << self 
      def get_all_pending_requests(current_user)
        User.joins(:friends)
        .where(friends: {friend_id: current_user.id, request_status: 'pending'})
        .pluck('friends.id','users.id','users.email')
      end

      def get_all_user_friends(current_user)
        User.joins(:friends)
        .where('friends.user_id = ? OR friends.friend_id = ?', current_user.id, current_user.id)
        .where(friends: {request_status: Friend::APPROVE})
        .where.not(friends: {friendship_status: Friend::BLOCK})     
        .pluck('friends.id', 'friends.friend_id', 'users.email')
        .map {|friend_tbl_id, friend_id, email| {friend_tbl_id: friend_tbl_id, friend_id: friend_id, email: email}}
      end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_rich_text :content
    has_many_attached :post_images, dependent: :destroy


    has_many :user_like_posts , dependent: :destroy
    has_many :users , through: :user_like_posts

    has_many :suggestions , as: :suggestionable
end

app/models/setting.rb
class Setting < ApplicationRecord
    belongs_to :user
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :user
  belongs_to :suggestionable, polymorphic: true
end

app/models/third_party_api.rb
class ThirdPartyApi < ApplicationRecord
    class << self
        def rest_countries_api
            'https://restcountries.com/v3.1/all'
        end

        def city_api_by_country_name(country_code)
            "http://api.geonames.org/searchJSON?country=#{country_code}&maxRows=1000&username=haris"
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :setting , dependent: :destroy
  has_one_attached :profile_photo, dependent: :destroy
  has_many :friends , dependent: :destroy
  has_many :posts , dependent: :destroy
  has_many :suggestions , dependent: :destroy

# many to many for post likes
  has_many :user_like_posts , dependent: :destroy
  has_many :post , through: :user_like_posts

  after_create do
     Setting.create(user_id: self.id) if self.id.present?
  end      

  def full_name
    first_name.present? || last_name.present? ? "#{first_name} #{last_name}" : email
  end
  
end

app/models/user_like_post.rb
class UserLikePost < ApplicationRecord
    belongs_to :user 
    belongs_to :post
end

app/controllers/a_controller.rb
class AController < ApplicationController




   
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  @suggestions = User.includes(:suggestions)
                     .where(suggestions: {suggestionable_id: params[:id]})
                     .includes(:posts)
                     .pluck("suggestions.content", "users.email")
                     .map{|suggestion_content, user_email| {suggestion_content: suggestion_content, user_email: user_email}}

  @suggestions.uniq!
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    # @post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def like_or_unlike_post
      if params[:action_performable] == 'like'
         save_like = current_user.user_like_posts.build(post_id: params[:id])
         redirect_to instagram_landing_page_path if save_like.save!
      else
        delete_like = current_user.user_like_posts.where(post_id: params[:id])
        redirect_to instagram_landing_page_path if delete_like.delete_all
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit!
    end
end

app/helpers/a_helper.rb
module AHelper
end

app/helpers/b1s_helper.rb
module B1sHelper
end

app/helpers/b2s_helper.rb
module B2sHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
    def request_status(u)
      Friend.find_by(user_id: [current_user.id, u.id], friend_id: [u.id, current_user.id], request_status: 'pending').present? ? true : false
    end

    def friend_email(id)
      User.find(id).email
    end
end

app/helpers/instagram_helper.rb
module InstagramHelper
    def page_number(sum)
        sum = sum + 1
    end

    def user_photo(u)
    return "no_photo.webp" unless u.profile_photo
    u.profile_photo if u.profile_photo.present?
    end

    def user_like_this_post(post)
        current_user.user_like_posts.where(post_id: post.id).present?
    end

    def total_likes(post)
      post.user_like_posts.count
    end

    def total_suggestion(post)
        post.suggestions.count
    end
end

app/helpers/posts_helper.rb
module PostsHelper

    def post_user(post)
        post.user == current_user ? 'You' : post.user.email
    end

    def users_post(post)
       post.user == current_user
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/suggestion_helper.rb
module SuggestionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_action_links.html.erb
<div>
  <%= link_to "Edit this post", edit_post_path(post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", post, method: :delete %>
</div>

<br><br>

app/views/posts/_form.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="modal" data-action="turbo:submit-end->modal#closeModal" style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: #fff; border: 1px solid #000; padding: 20px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); z-index: 999;">
<%= link_to 'Back' , :back %>
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
  <%= form.label :attact_images, style: "display: block" %>
  <%= form.file_field :post_images , multiple: true%>
</div>
  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

</div>
<% end %>

app/views/posts/_landing_page_post.html.erb
<div id="<%= dom_id post %>">
<strong>Post by: <%= post_user(post) %> </strong>
<p>
    <strong>Attachments:</strong>
    <%= render "posts/post_images" , :images => post.post_images if post.post_images.present? %>
  </p>
<p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

<h3>Total likes: <%= total_likes(post) %> | Total comments: <%= total_suggestion(post) %></h3>

<%= render partial: "posts/like_or_unlike" , locals: {post: post} %>

<%= link_to 'Show this post' , post_path(post) %>

app/views/posts/_like_or_unlike.html.erb
<%= button_to 'Like', like_or_unlike_post_post_path(id: post.id, action_performable: 'like') unless user_like_this_post(post) %>
<%= button_to 'unlike', like_or_unlike_post_post_path(id: post.id, action_performable: 'unlike') if user_like_this_post(post) %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
<strong>Post by: <%= post_user(post) %> </strong>
<p>
    <strong>Attachments:</strong>
    <%= render "posts/post_images" , :images => post.post_images if post.post_images.present? %>
  </p>
<p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

</div>

app/views/posts/_post_images.html.erb
<% images.each do |img| %>
   <span> <%= image_tag img , style: " width: 180px; height: 180px;" %> </span>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<%= render partial: "posts/action_links", locals: {post: @post} if users_post(@post) %> 

<%= render partial: "suggestion/suggestion", locals: {post: @post} %> 

<%= render partial: "suggestion/all_suggestions", locals: {suggestions: @suggestions} %>