config/routes.rb
Rails.application.routes.draw do
  resources :b2s
  resources :posts do
    member do
      post :like_or_unlike_post
    end
  end
  resources :settings
  devise_for :users
  root 'instagram#home_page'
  get 'instagram/landing_page'
  
  
  get 'users/profile' , as: :user_profile
  post 'users/update_profile' , as: :update_user_profile
  
  # post 'friends/friend_request' , as: :friend_request
  
  resources :friends do
    member do
      post :friend_request
      post :approve_request
      post :reject_request
      post :block_or_unfriend
      post :unblock_user
    end
    
    collection do
      get :pending_requests
      get :user_friends
      get :blocked_users
    end
  end
  
  
  post 'suggestion/create_suggestion'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/action.rb
class Action < ApplicationRecord
 
    self.table_name = "active_storage_variant_records"

end

app/models/b1.rb
class B1 < ApplicationRecord
end

app/models/b2.rb
class B2 < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
    APPROVE, REJECT, FRIEND, UNFRIEND, PENDING, BLOCK = 'approve', 'reject', 'friend', 'unfriend', 'pending', 'block'
    

    class << self 
      def get_all_pending_requests(current_user)
        User.joins(:friends)
        .where(friends: {friend_id: current_user.id, request_status: 'pending'})
        .pluck('friends.id','users.id','users.email')
      end

      def get_all_user_friends(current_user)
        User.joins(:friends)
        .where('friends.user_id = ? OR friends.friend_id = ?', current_user.id, current_user.id)
        .where(friends: {request_status: Friend::APPROVE})
        .where.not(friends: {friendship_status: Friend::BLOCK})     
        .pluck('friends.id', 'friends.friend_id', 'users.email')
        .map {|friend_tbl_id, friend_id, email| {friend_tbl_id: friend_tbl_id, friend_id: friend_id, email: email}}
      end
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_rich_text :content
    has_many_attached :post_images, dependent: :destroy


    has_many :user_like_posts , dependent: :destroy
    has_many :users , through: :user_like_posts

    has_many :suggestions , as: :suggestionable
end

app/models/setting.rb
class Setting < ApplicationRecord
    belongs_to :user
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :user
  belongs_to :suggestionable, polymorphic: true
end

app/models/third_party_api.rb
class ThirdPartyApi < ApplicationRecord
    class << self
        def rest_countries_api
            'https://restcountries.com/v3.1/all'
        end

        def city_api_by_country_name(country_code)
            "http://api.geonames.org/searchJSON?country=#{country_code}&maxRows=1000&username=haris"
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :setting , dependent: :destroy
  has_one_attached :profile_photo, dependent: :destroy
  has_many :friends , dependent: :destroy
  has_many :posts , dependent: :destroy
  has_many :suggestions , dependent: :destroy

# many to many for post likes
  has_many :user_like_posts , dependent: :destroy
  has_many :post , through: :user_like_posts

  after_create do
     Setting.create(user_id: self.id) if self.id.present?
  end      

  def full_name
    first_name.present? || last_name.present? ? "#{first_name} #{last_name}" : email
  end
  
end

app/models/user_like_post.rb
class UserLikePost < ApplicationRecord
    belongs_to :user 
    belongs_to :post
end

app/controllers/a_controller.rb
class AController < ApplicationController




   
    
end

app/controllers/instagram_controller.rb
class InstagramController < ApplicationController
  def home_page
  end

  def landing_page
      suggestion_users()
      @posts = Post.all.order(id: :desc)
      @sum = 0
  end
end

app/helpers/a_helper.rb
module AHelper
end

app/helpers/b1s_helper.rb
module B1sHelper
end

app/helpers/b2s_helper.rb
module B2sHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
    
    def request_status(u)
      Friend.find_by(user_id: [current_user.id, u.id], friend_id: [u.id, current_user.id], request_status: 'pending').present? ? true : false
    end

    def friend_email(id)
      User.find(id).email
    end
end

app/helpers/instagram_helper.rb
module InstagramHelper
    def page_number(sum)
        sum = sum + 1
    end

    def user_photo(u)
    return "no_photo.webp" unless u.profile_photo
    u.profile_photo if u.profile_photo.present?
    end

    def user_like_this_post(post)
        current_user.user_like_posts.where(post_id: post.id).present?
    end

    def total_likes(post)
      post.user_like_posts.count
    end

    def total_suggestion(post)
        post.suggestions.count
    end
end

app/helpers/posts_helper.rb
module PostsHelper

    def post_user(post)
        post.user == current_user ? 'You' : post.user.email
    end

    def users_post(post)
       post.user == current_user
    end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/instagram/_card.html.erb
<% suggestion_users.each do |u| %>
    <div class="card">
    <%= image_tag u.profile_photo, style: "border-radius: 50%; width: 150px; height: 150px;" if u&.profile_photo.present? %>
    <%= image_tag "no_photo.webp", style: "border-radius: 50%; width: 150px; height: 150px;" unless u&.profile_photo.present? %>
    <div class="container">
            <h4><b><%= u&.full_name %></b></h4> 
            <% if request_status(u) %>
               <%= link_to 'Requested' %> 
            <% else %>
               <%= button_to 'Add Friend' , friend_request_friend_path(u.id) %> 
            <% end %>
        </div>
    </div>
<% end %>
   

app/views/instagram/_slider.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card Slider</title>
</head>
<body>

    <div class="slider-container">
        <div class="slider-wrapper" id = "updated_card">
          <%= render partial: 'instagram/card', locals: {suggestion_users: suggestion_users} %>
          </div>
    </div>

    <div class="slider-controls">
        <p onclick="slide('prev')">Previous</p>
        <p onclick="slide('next')">Next</p>
    </div>
</body>
</html>



<script>

const sliderWrapper = document.querySelector('.slider-wrapper');
let currentPosition = 0;

function slide(direction) {
    const cardWidth = document.querySelector('.card').offsetWidth + 20; // 20px for margin
    if (direction === 'next' && currentPosition > -(cardWidth * 2)) {
        currentPosition -= cardWidth;
    } else if (direction === 'prev' && currentPosition < 0) {
        currentPosition += cardWidth;
    }
    sliderWrapper.style.transform = `translateX(${currentPosition}px)`;
}

</script>

app/views/instagram/home_page.html.erb
<h1>Instagram</h1>

<span>
<%= link_to "Login" , new_user_session_path %> || <%= link_to "Signup" , new_user_registration_path %>
</span>

app/views/instagram/landing_page.html.erb
<h1><%= link_to current_user.email , user_profile_path %></h1>


<span>
    <%= link_to 'Add Post', new_post_path, data: {turbo_frame: "modal"} %> | 
    <%= link_to 'Inbox' %> | 
    <%= link_to 'Friend' , user_friends_friends_path , data: {turbo_frame: "modal"} %> |
    <%= link_to 'Friend Requests' , pending_requests_friends_path , data: {turbo_frame: "modal"}  %> |
    <%= link_to 'Block Users' , blocked_users_friends_path , data: {turbo_frame: "modal"} %> |
    <%= link_to 'Search People' %> |
    <%= link_to 'Settings' , edit_setting_path(current_user.setting.id) , data: {turbo_frame: "modal"} %>
</span>

<br><br><br><br>
<strong>Suggestions-Add Friends</strong>
<br>

<%= render partial: "instagram/slider", locals: {suggestion_users: @suggestion_users} if @suggestion_users.present?%>

<h1>All Posts</h1>

<div>
  <% @posts.each do |post| %>
    <h1>Post#: <%= @sum = @sum + 1 %></h1>
    <%= render "posts/landing_page_post" , :post => post %>
    <p>
      <h3>-----------------------------------------------</h3>
    </p>
  <% end %>
</div>